### ISSUE TITLE
Action Needed: check SSH key age

### ISSUE THREAD

**Issue by ghost** [mozilla/admin_for_mozilla#1]
@mozilla/admin-all-org-members <= all Mozilla org members.
## Warning

On Tuesday, 2015-10-20, we will enable some new security settings on the Mozilla organization ([see post](https://groups.google.com/forum/#!topic/mozilla.dev.platform/UjutypdmWss)).
If your SSH key was linked to your github account prior to February of 2014, **it _MAY NOT_ be accepted any longer**, and you will not have access to the mozilla organization until you upload a new key.
## How to check if you'll be impacted
- Go to your [ssh settings](https://github.com/settings/ssh)
- If you see a warning, you will be impacted. Please fix as directed.
- If you see an "Added on" date before February 2014, **you will be impacted**. Please re-upload your key!
### Notes
- Some folks are reporting they have an older key, and do not have a warning. I'm seeking clarification from github support on this, but likely won't have an answer until Monday.
- I know (from personal experience) that if you're locked out, you do have a warning.
- All that is needed is to re-upload the key, not regenerate (unless github gives you further warnings)
  - if you do regenerate, please see [EIS's handy suggestions](https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Key_generation) (thanks, Kang!)

**Comment by jruderman** [comment]
https://github.com/settings/ssh says my key was added in 2012, but I don't
see a warning...

On Fri, Oct 16, 2015 at 11:35 AM, Hal Wine (admin) <notifications@github.com

**Comment by mykmelez** [comment]
> https://github.com/settings/ssh says my key was added in 2012, but I don't
> see a warning...

Hmm, that page doesn't tell me when my key was added. Perhaps because I added it more recently (although I thought I did so years ago). Can you provide the exact text of the message (or a screenshot)?

**Comment by gdestuynder** [comment]
If generating a new key, while you're at it, have a look at https://wiki.mozilla.org/Security/Key_Management and/or https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Key_generation

Also, deep-linked from the initial comment: https://help.github.com/articles/about-third-party-application-restrictions/

**Comment by TimAbraldes** [comment]
I see " Added on Mar 22, 2013" but I don't see any kind of error message

**Comment by kyoshino** [comment]
Same here, my key was "Added on Nov 30, 2012" but no warnings. Will update it anyway.

**Comment by KWierso** [comment]
If it has a green check mark next to it, I think it's fine. If it has accept/reject buttons, you need to verify it.

**Comment by mykmelez** [comment]
> If it has a green check mark next to it, I think it's fine. If it has accept/reject buttons, you need to verify it.

I don't have a check mark, but I do have a dot. is.gd?

<img width="294" alt="screen shot 2015-10-16 at 18 05 54" src="https://cloud.githubusercontent.com/assets/305455/10556138/991955f8-7430-11e5-9dcf-a735b6dfc680.png">

**Comment by tonymec** [comment]
I'm not using local clones of github repositories at the moment (for Vim I use the Mercurial mirror on bitbucket, and that only for pull and not push; for my own fork of mozilla/nightlytt I use only the web interface) so IIUC my SSH key can stay disabled.

Best regards,
Tony.

**Comment by indygreg** [comment]
This is also a good time to audit the type and strength of your SSH keys.

Look in `~/.ssh/` for `id_*` files. Then `ssh-keygen -l -f <file>` to print key info. e.g. `ssh-keygen -l -f ~/.ssh/id_rsa`. If you have DSA keys or if you have a RSA key and the first integer is 1024 or smaller, **you should stop what you are doing and regenerate SSH keys** because your keys aren't that strong.

https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Key_generation says how to generate secure keys. A number of SSH servers don't yet support ed25519, so 4096 byte RSA is probably your best bet.

SSH keys registered with Mozilla can be updated at https://login.mozilla.com/. No need to file a bug and wait for someone to update your keys.

**Comment by sole** [comment]
hi, I've added your info to the wiki page as I think it will do good there and not be lost in e-mails/github issues

https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Key_generation

I also added a new section for key auditing
https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Auditing_your_existing_machine_keys

I don't know what is the purpose of updating keys to login.m.o, so I didn't add that bit - care to explain?

**Comment by selenamarie** [comment]
@sole SSH keys for logging into IT-managed infrastructure are distributed through login.m.o.

**Comment by jvehent** [comment]
login.m.o stores public ssh keys in LDAP. IT puppet uses it to distribute to its systems, and I'm working on an integration to use it in Cloud Services too. Not sure if releng uses it yet, but it should :)

**Comment by vvuk** [comment]
Also, OpenSSH >= 7 stops offering DSA keys by default (need to explicitly
set PubkeyAcceptedKeyTypes to ssh-dss).  So it's a good time to start
migrating off of DSA keys.

```
- Vlad
```

**Comment by djmitche** [comment]
Releng uses it too.

**Comment by dmose** [comment]
I have an old key, which has a grey dot, but no warning and no checkmark.  I generated a new key this morning (4096-bit RSA) and submitted it to github, and it looks exactly the same (grey dot, no warning, no checkmark).  

It also appears to be impossible to update your own key on login.mozilla.com unless you've got a Mozilla 2-factor auth token.

**Comment by joewalker** [comment]
If you use the key does it turn green?
I think the green/grey distinction relates to how recently it was used. The
idea being that you should remove access to anything that you're not
actively using.

Joe.

**Comment by indygreg** [comment]
@dmose login.mozilla.com requires 2FA for a number of operations as of a few weeks ago. You should go to the "Multi Factor Authentication" section of login.mozilla.com and enroll a new device. A lot of the docs say to use Duo. But it's TOTP, so apps like Google Authenticator work just fine.

The reason 2FA is required to modify SSH keys is because if it weren't, a compromise of just your username/password could lead to someone installing a new SSH key and gaining access to servers or services (assuming they aren't using 2FA for login - which some SSH servers at Mozilla now do).

**Comment by fmarier** [comment]
> You should go to the "Multi Factor Authentication" section of login.mozilla.com and enroll a new device. A lot of the docs say to use Duo. But it's TOTP, so apps like Google Authenticator work just fine.

I don't see this "Multi Factor Authentication" section. I've only got these sections when I visit https://login.mozilla.com:
- Dashboard
- LDAP Password Reset
- SSH Keys
- PGP Fingerprint
- OpenVPN

**Comment by gdestuynder** [comment]
As an update to @fmarier's comment - currently to get the MFA panel on login.mozilla.com you need to get added to that group. In the future I expect everyone will get it by default. If you need to be added, you might have to fill a bug to https://bugzilla.mozilla.org/enter_bug.cgi?product=Infrastructure%20%26%20Operations&component=Infrastructure%3A%20Other in the mean time

**Comment by dmose** [comment]
@joewalker I've used the old key within the last three weeks, and it's not green.  I'll try the new one.

**Comment by nils-ohlmeier** [comment]
My key had a green dot last week when I checked. It had a grey dot next to it this morning when I checked again to upload a new key.
Doing a ‘ssh -T git@github.com’ turns the dot green, as the mouse over tells you green means the key was successfully used within the last 7 days.

**Comment by sr-murthy** [comment]
I recently deleted my old keys and generated a new key, which I've activated, so it has a green dot.

**Comment by dmose** [comment]
OK, got it all sorted.  Thanks, y'all!

**Comment by SimonSapin** [comment]
_Removing_ keys should not require 2FA. My laptop was stolen a few days ago. I changed my LDAP password, but did not bother setting up 2FA just to remove the SSH key in LDAP that I haven't used in months.

**Comment by gdestuynder** [comment]
update to the login.mozilla.com situation, everyone is in the group now so it functions as previously expected :)

**Comment by skinny97214** [comment]
Please, for please, stop hitting reply all and including my personal email.

Love,
c

**Comment by slifty** [comment]
(You can easily "mute" conversations in most mail clients)

I'm super nerdy but I like hearing these kinds of conversations ;)

**Comment by jryans** [comment]
I think all that's needed is to visit this issue page and click "Unsubscribe" to end future notifications.

**Comment by vladikoff** [comment]
> update to the login.mozilla.com situation, everyone is in the group now so it functions as previously expected :)

Still not seeing it, is it under an existing section or a new section?

**Comment by jaredhirsch** [comment]
@skinny97214 I (finally, belatedly) removed you from the mozilla github org, enjoy your eternal sunshine of the spotless inbox

**Comment by mbrubeck** [comment]
If you are receiving this message by email, it's because GitHub automatically subscribed you to this issue:
https://github.com/mozilla/admin_for_mozilla/issues/1

You can unsubscribe by clicking the link above and then pressing the "Unsubscribe" button in the sidebar.

**Comment by indygreg** [comment]
We flipped the settings change on the mozilla org ~30 minutes ago. Join #github on irc.mozilla.org or email github-owners@mozilla.org if you see issues.

Now might be a good time to check your hooks, apps, services, etc are working correctly. If something broke today, it is almost certainly related to this change.

**Comment by ghost** [comment]
All done - for any further questions please refer to [wikimo Github page](https://wiki.mozilla.org/Github).
